name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build and analyse iOS app using xcodebuild
    runs-on: macos-14

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install xcpretty
        run: gem install xcpretty

      - name: Run Tests
        run: |
          xcodebuild test \
            -scheme "ETPattern" \
            -project "ETPattern.xcodeproj" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
            | xcpretty && exit ${PIPESTATUS[0]}

      - name: Build for iOS Simulator
        run: |
          xcodebuild clean build analyze \
            -scheme "ETPattern" \
            -project "ETPattern.xcodeproj" \
            -sdk iphonesimulator \
            -configuration Debug \
            -destination "platform=iOS Simulator,name=iPhone 16,OS=latest" \
            | xcpretty && exit ${PIPESTATUS[0]}
